apps/urls.py
from django.urls import path

from apps.views import ProductListView, ProductDetailView, WishlistView, OrderView, OrderedView, \
    WishlistShowView, WishlistRemoveView, MarketListView, SendMailView, FilteredCategoriesListView, StreamListView, \
    StreamDetailView, OrderListView, OrderDetailView
from apps.views.operator_view import BaseOperatorListView

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product-detail/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('market/', MarketListView.as_view(), name='market'),
    path('category/<int:pk>', ProductListView.as_view(), name='products_list'),
    path('category', FilteredCategoriesListView.as_view(), name='categories_list'),
    path('send_mails/', SendMailView.as_view(), name='send'),
    path('wishlist/add/<int:product_id>', WishlistView.as_view(), name='wishlist_create'),
    path('order', OrderView.as_view(), name='order'),
    path('ordered_list', OrderListView.as_view(), name='ordered_list'),
    path('ordered/<int:pk>', OrderedView.as_view(), name='ordered'),
    path('ordered_detail/<int:pk>', OrderDetailView.as_view(), name='ordered_detail'),
    path('liking', WishlistShowView.as_view(), name='wishlist_list'),
    path('liking/delete/<int:product_id>', WishlistRemoveView.as_view(), name='deleting_wishlist'),
    path('stream/', StreamListView.as_view(), name='stream'),
    path('stream/<int:pk>/', StreamDetailView.as_view(), name='stream_detail'),
]


urlpatterns += [
    path('operator/new/', BaseOperatorListView.as_view(), name='orders_list'),
]

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import path, include




def logout_v(req):
    logout(req)
    return redirect('product_list')


urlpatterns = [
    path('admin/logout/', logout_v),
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('auth/', include('users.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/models/products.py
from datetime import timedelta

from ckeditor.fields import RichTextField
from django.db import models
from django.db.models import CharField, DecimalField, ForeignKey, CASCADE, JSONField, \
    PositiveIntegerField, IntegerField, SlugField
from django.utils.text import slugify
from django.utils.timezone import now
from django_resized import ResizedImageField

from apps.models import BaseModel


class Product(BaseModel):
    name = CharField(max_length=255)
    price = DecimalField(max_digits=10, decimal_places=2)
    slug = SlugField(max_length=255, null=True, blank=True, editable=False)
    Description = RichTextField()
    category = ForeignKey('apps.Category', CASCADE, related_name='products')
    discount = IntegerField()
    characteristics = JSONField(default=dict)
    quantity = PositiveIntegerField(default=0)
    site_settings = ForeignKey('apps.SiteSettings', CASCADE, 'site_settings')

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Product.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug}-{num}'
            num += 1
        return unique_slug

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = self._get_unique_slug()
        if force_update is True:
            self.slug = slugify(self.name)
        return super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'mahsulot'
        verbose_name_plural = 'mahsulotlar'
        ordering = ('-created_at',)

    @property
    def is_available(self):
        return self.quantity > 0

    @property
    def discount_price(self):
        return self.price * self.discount / 100

    @property
    def sell_price(self):
        return self.price - self.discount_price

    @property
    def is_new(self):
        return self.created_at >= now() - timedelta(days=2)

    @property
    def add_shipping(self):
        return self.sell_price + 30000


class ProductImage(models.Model):
    image = ResizedImageField(size=[1098, 717], upload_to='images/products', null=True, blank=True)
    product = models.ForeignKey('apps.Product', models.CASCADE, related_name='images')

    def __repr__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Mahsulot Rasmi'
        verbose_name_plural = 'Mahsulot Rasmlari'

apps/views/operator_view.py
from apps.models import Order
from django.views.generic import ListView


class BaseOperatorListView(ListView):
    queryset = Order.objects.all()
    template_name = 'apps/../../templates/operators/operator.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return super().get_queryset().filter(status=Order.Status.NEW)

templates/operators/operator.html
{% extends 'base/operator_base.html' %}
{% load static %}
{% block operator_content %}
    <div class="col-md-10" style="margin-left: 16%;">
        <div class="bg-light w-75 m-auto mt-5">
            <form method="GET">
                <div>
                    <p>
                        <label for="id_product">Mahsulot:</label>
                        <select name="product" id="id_product" multiple>
                            {% for order in all_orders %}
                                <option value="1">{{ order.product.name }}</option>
                            {% endfor %}
                        </select>


                    </p>


                    <p>
                        <label for="id_location">Viloyat:</label>
                        <select name="location" id="id_location" multiple>
                            <option value="Viloyatni tanlang">Viloyatni tanlang</option>
                            {% for region in regions %}
                                <option value="tashkent">{{ region.name }}</option>
                            {% endfor %}


                        </select>


                    </p>


                    <p>
                        <label for="id_region">Tuman:</label>
                        <select name="region" id="id_region" multiple>
                            {% for district in districts %}
                                <option value="Amudaryo tumani">{{ district.name }}</option>
                            {% endfor %}


                        </select>


                    </p>


                    <p>
                        <label for="id_name">Mahsulot nomi:</label>
                        <input type="text" name="name" id="id_name">


                    </p></div>
                <input class="btn btn-primary" type="submit" value="Saqlash">
            </form>
            {% for order in all_orders %}
                <div class="card border-dark mt-5">
                    <div class="card-body">
                        <h2 class="card-title">{{ order.product.name }} - {{ order.product.price }} so'm</h2>
                        <ul class="text-muted">
                            <li class="">Client: {{ order.user.first_name }} {{ order.user.last_name }}
                                - {{ order.user.phone_number }}</li>
                            <li class="">Address: Viloyatni tanlang</li>
                            <li class="">Narxi: {{ order.product.price }} so'm <strong>+ 30000</strong> so'm</li>
                            <li class="">Soni: {{ order.quantity }}ta</li>
                            <li class="">Komment: {{ order.comment }}</li>

                            <li class="">ID: #{{ order.id }}</li>
                            <li class="">Vaqti: {{ order.created_at }}</li>
                            <li class="">Yangilangan vaqti: {{ order.updated_at }}</li>
                            <li class="text-dark">Holati: {{ order.get_status_display }}</li>
                        </ul>

                    </div>
                </div>
            {% endfor %}

            <div class="card-footer bg-light d-flex justify-content-center">
                <div>
                    {% if page_obj.has_previous %}
                        <a class="btn btn-sm btn-falcon-default me-2"
                           href="?page={{ page_obj.previous_page_number }}">
                            <span class="fas fa-chevron-left"></span>
                        </a>
                        <a class="btn btn-sm btn-falcon-default me-2"
                           href="?page={{ page_obj.previous_page_number }}">
                            {{ page_obj.previous_page_number }}
                        </a>
                    {% endif %}
                    <a class="btn btn-sm btn-falcon-default text-primary me-2" href="#">{{ page_obj.number }}</a>
                    {% if page_obj.has_next %}
                        <a class="btn btn-sm btn-falcon-default me-2" href="?page={{ page_obj.next_page_number }}">
                            {{ page_obj.next_page_number }}
                        </a>
                        <a class="btn btn-sm btn-falcon-default me-2" href="?page={{ page_obj.next_page_number }}">
                            <span class="fas fa-chevron-right"></span>
                        </a>
                    {% endif %}
                </div>
            </div>

        </div>


    </div>
{% endblock %}