apps/urls.py
from django.urls import path

from apps.views import ProductListView, ProductDetailView, WishlistView, OrderView, OrderedView, \
    WishlistShowView, WishlistRemoveView, MarketListView, SendMailView, FilteredCategoriesListView, StreamListView, \
    StreamDetailView, OrderListView, OrderDetailView
from apps.views.operator_view import BaseOperatorListView

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product-detail/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('market/', MarketListView.as_view(), name='market'),
    path('category/<int:pk>', ProductListView.as_view(), name='products_list'),
    path('category', FilteredCategoriesListView.as_view(), name='categories_list'),
    path('send_mails/', SendMailView.as_view(), name='send'),
    path('wishlist/add/<int:product_id>', WishlistView.as_view(), name='wishlist_create'),
    path('order', OrderView.as_view(), name='order'),
    path('ordered_list', OrderListView.as_view(), name='ordered_list'),
    path('ordered/<int:pk>', OrderedView.as_view(), name='ordered'),
    path('ordered_detail/<int:pk>', OrderDetailView.as_view(), name='ordered_detail'),
    path('liking', WishlistShowView.as_view(), name='wishlist_list'),
    path('liking/delete/<int:product_id>', WishlistRemoveView.as_view(), name='deleting_wishlist'),
    path('stream/', StreamListView.as_view(), name='stream'),
    path('stream/<int:pk>/', StreamDetailView.as_view(), name='stream_detail'),
]


urlpatterns += [
    path('operator/new/', BaseOperatorListView.as_view(), name='orders_list'),
]

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import path, include




def logout_v(req):
    logout(req)
    return redirect('product_list')


urlpatterns = [
    path('admin/logout/', logout_v),
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('auth/', include('users.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/models/product_addings.py
from django.db import models
from django.db.models import (Model, CharField, DateTimeField,
                              ForeignKey, CASCADE, ImageField,
                              PositiveIntegerField, SlugField)
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.utils.text import slugify

from apps.models import BaseModel


class Category(MPTTModel, BaseModel):
    name = CharField(max_length=255, unique=True)
    image = ImageField(upload_to='media/categories', null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = SlugField(max_length=255, null=True, blank=True, editable=False)

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug}-{num}'
            num += 1
        return unique_slug

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = self._get_unique_slug()
        if force_update is True:
            self.slug = slugify(self.name)
        return super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f'{self.name}'

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'kategoriya'
        verbose_name_plural = 'kategoriyalar'

        constraints = [
            models.UniqueConstraint(fields=['slug'], name='unique_slug')
        ]


class Wishlist(BaseModel):
    user = ForeignKey('users.CustomUser', CASCADE)
    product = ForeignKey('apps.Product', CASCADE, 'wishlists')
    added_at = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.product}'

    class Meta:
        verbose_name = 'sevimli'
        verbose_name_plural = 'sevimlilar'


class Cart(BaseModel):
    user = ForeignKey('users.CustomUser', CASCADE)
    product = ForeignKey('apps.Product', CASCADE, 'products')
    quantity = PositiveIntegerField(default=1)
    added_at = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} ning savatida: {self.product.name} x {self.quantity}'

    class Meta:
        verbose_name = 'savatcha'
        verbose_name_plural = 'savatchalar'


class Order(BaseModel):
    class Status(models.TextChoices):
        NEW = 'yangi'
        READY = 'dostavkaga tayyor'
        DELIVERING = 'yetkazilmoqda'
        DELIVERED = 'yetkazib berildi'
        ARCHIVE = 'arxivlandi'
        CANCELLED = 'bekor qilindi'
        BROKEN = 'nosoz'
        ARRIVED = 'qaytib keldi'
        WAITING = 'keyin oladi'

    name = CharField(max_length=255)
    phone_number = CharField(max_length=20)
    product = ForeignKey('apps.Product', CASCADE)
    quantity = PositiveIntegerField(default=1)
    status = CharField(max_length=55, choices=Status, default=Status.NEW)

    class Meta:
        verbose_name = 'buyurtma'
        verbose_name_plural = 'buyurtmalar'


class SiteSettings(BaseModel):
    shipping_change = PositiveIntegerField()

    class Meta:
        verbose_name = 'Sahifa sozlamasi'
        verbose_name_plural = 'Sahifa sozlamalari'

    def __str__(self):
        return f'yetkazib berish - {self.shipping_change}'


class Threads(Model):
    name = CharField(max_length=255)
    user = ForeignKey('users.CustomUser', CASCADE, related_name='threads')
    product = ForeignKey('apps.Product', CASCADE)

    class Meta:
        verbose_name = 'oqim'
        verbose_name_plural = 'oqimlar ro"yxati'

    def __str__(self):
        return f'{self.product.name} --> {self.user}'

templates/apps/categories.html
{% extends 'base/base2.html' %}
{% load static %}
{% block title %}Wishlist list{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <div class="row justify-content-between">
                <div class="col-md-auto">
                    <h5 class="mb-3 mb-md-0">Shopping Cart (7 Items)</h5>
                </div>
                <div class="col-md-auto"><a class="btn btn-sm btn-outline-secondary border-300 me-2"
                                            href="app/e-commerce/product/product-list.html"> <span
                        class="fas fa-chevron-left me-1" data-fa-transform="shrink-4"></span>Continue Shopping</a><a
                        class="btn btn-sm btn-primary" href="app/e-commerce/checkout.html">Checkout</a></div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="row gx-card mx-0 bg-200 text-900 fs--1 fw-semi-bold">
                <div class="col-9 col-md-8 py-2">Name</div>
                <div class="col-3 col-md-4">
                    <div class="row">
                        <div class="col-md-8 py-2 d-none d-md-block text-center">Picture</div>
                        <div class="col-12 col-md-4 text-end py-2">Price</div>
                    </div>
                </div>
            </div>
            {% for produkt in object_list %}
                <div class="row gx-card mx-0 align-items-center border-bottom border-300">
                    <div class="col-8 py-3">
                        <div class="d-flex align-items-center"><a
                                href="app/e-commerce/product/product-details.html"><img
                                class="img-fluid rounded-1 me-3 d-none d-md-block"
                                src="{{ produkt.images.first.image.url }}" alt="" width="60"/></a>
                            <div class="flex-1">
                                <h5 class="fs-0"><a class="text-900"
                                                    href="app/e-commerce/product/product-details.html">{{ produkt.name }}</a>
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 py-3">
                        <div class="row align-items-center">
                            <div class="col-md-4 text-end ps-0 order-0 order-md-1 mb-2 mb-md-0 text-600">
                                ${{ produkt.sell_price }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/apps/market.html
{% extends 'base/base2.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="card-body">
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Oqim yaratish</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{% url 'stream' %}" class="form-class">
                            {% csrf_token %}
                            <input  id="hidden_product" value="test" name="product">
                            Oqim nomi <input type="text" name="name" class="form-control" placeholder="">
                            Chegirma <input type="text" name="discount" class="form-control" placeholder="">
                            Qo'shimcha foyda <input type="text" name="additional_benefit" class="form-control"
                                                    placeholder="">
                            Pullik dostavka <input type="checkbox" name="paid_delivery" id="id_paid_delivery">
                            <input type="submit" class="btn btn-primary mt-4" value="Oqim yaratish">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <br>
            <br>
            <h3 class="text-center"> Hozirda sotuvda bor <br> mahsulotlar </h3>
            <br>

            <div class="container border-bottom-4">
                <div class="header_tab_menu">
                    <div class="header_menu" style="overflow: auto">
                        <a href="/admin_page/market/" class="active btn btn-default"> Hammasi </a>
                        {% for category in categories %}
                            <a href="" class="btn btn-default"> {{ category.name }} </a>
                        {% endfor %}
                    </div>
                    <div class="search-box" style="width: 100%;">
                        <form action="/admin_page/market/" method="GET" class="position-relative" style="width: 100%"
                              data-bs-display="static" autocomplete="off">
                            <input type="hidden" name="csrfmiddlewaretoken"
                                   value="7EuuwKVbGxHsOsMSizO6UgKjBfj5hBUgzMopUS6mmRDuwOA1fMn4vUaEjLpC8ilI">
                            <input id="search-input" name="q" class="form-control search-input" type="search"
                                   placeholder="Qidiruv..." aria-label="Search">
                            <svg class="svg-inline--fa fa-search fa-w-16 search-box-icon" aria-hidden="true"
                                 focusable="false" data-prefix="fas" data-icon="search" role="img"
                                 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                      d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                            </svg>
                            <!-- <span class="fas fa-search search-box-icon" aria-hidden="true"></span> Font Awesome fontawesome.com -->
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                {% for market in market_list %}


                    <div class="col-sm-4 p-2">
                        <div class="card">
                            <a href="{% url 'stream_detail' market.pk %}" target="_blank">
                                <img class="card-img-top" src="{{ market.images.first.image.url }}" alt="{{ market.name }}">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{% url 'stream_detail' market.pk %}" target="_blank">
                                        {{ market.name }}
                                    </a>
                                </h5>
                                <p class="text-muted"> {{ market.sell_price }} so'm </p>
                            </div>

                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">To'lov: <strong> </strong></li>

                                <li class="list-group-item">Zaxirada: <strong> {{ market.quantity }} ta </strong>
                                </li>

                                <li class="list-group-item">Chegirma: <strong> yuq </strong>
                                </li>

                            </ul>

                            <!-- <form method="post"> <input type="hidden" name="csrfmiddlewaretoken" value="7EuuwKVbGxHsOsMSizO6UgKjBfj5hBUgzMopUS6mmRDuwOA1fMn4vUaEjLpC8ilI"> <input type="hidden" name="product_id" value="409"> <input type="submit" value="Oqim yaratish" class="btn btn-primary"> </form> -->

                            <a href="https://t.me/alijahon_uz_Internet_magazin/1400"
                               class="btn bg-danger text-white mt-2">Reklama
                                Posti</a>
                            <button class="btn btn-primary btn_open_modal" type="button" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal" name="{{ market.id }}">
                                Oqim yaratish
                            </button>
                            <a href="{% url 'stream_detail' market.pk %}" class="btn bg-danger text-white mt-2">Batafsil</a>
                        </div>
                    </div>
                {% endfor %}

                <nav aria-label="Page navigation example">
                    <ul class="pagination">


                        <div class="col-sm-auto mb-2 mb-sm-0">
                            <h6 class="mb-0">Showing {{ page_obj.start_index }}-{{ page_obj.end_index }}
                                of {{ page_obj.paginator.count }} Products</h6>
                        </div>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
	
    <script>
        $('.btn_open_modal').on('click', function () {
            let product_id = $(this).attr('name');
            console.log(product_id);
            $('#hidden_product').val(product_id);
        })
    </script>
{% endblock %}

templates/apps/order_product_detail.html
{% extends 'base/base2.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->

    </nav>
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6 mb-4 mb-lg-0">
                    <div class="product-slider" id="galleryTop">
                        <div class="swiper-container theme-slider position-lg-absolute all-0"
                             data-swiper='{"autoHeight":true,"spaceBetween":5,"loop":true,"loopedSlides":5,"thumb":{"spaceBetween":5,"slidesPerView":5,"loop":true,"freeMode":true,"grabCursor":true,"loopedSlides":5,"centeredSlides":true,"slideToClickedSlide":true,"watchSlidesVisibility":true,"watchSlidesProgress":true,"parent":"#galleryTop"},"slideToClickedSlide":true}'>
                            <div class="swiper-wrapper h-100">
                                {% for product_image in product.images.all %}
                                    <div class="swiper-slide h-100">
                                        <img class="rounded-1 fit-cover h-100 w-100"
                                             src="{{ product_image.image.url }}"
                                             alt=""/>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="swiper-nav">
                                <div class="swiper-button-next swiper-button-white"></div>
                                <div class="swiper-button-prev swiper-button-white"></div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-lg-6">
                    <h5>{{ product.name }}</h5><a class="fs--1 mb-2 d-block"
                                                  href="{% url 'product_list' %}">{{ product.category }}</a>
                    <div class="fs--2 mb-3 d-inline-block text-decoration-none"><span
                            {#                            class="fa fa-star text-warning"></span><span#}
                            {#                            class="fa fa-star text-warning"></span><span#}
                            {#                            class="fa fa-star text-warning"></span><span#}
                            {#                            class="fa fa-star text-warning"></span><span#}
                            {#                            class="fa fa-star-half-alt text-warning star-icon"></span><span#}
                            class="ms-1 text-600"></span>
                    </div>
                    <p class="fs--1">{{ product.description|safe }}</p>
                    <h4 class="d-flex align-items-center"><span
                            class="text-warning me-2">{{ product.sell_price }}</span><span
                            class="me-1 fs--1 text-500">
                      <del class="me-1">{{ product.price }}</del><strong>-{{ product.discount }}%</strong></span></h4>
                    <p class="fs--1 mb-1"><span>Shipping Cost: </span><strong>{{ product.site_settings }}</strong></p>
                    <p class="fs--1">Stock: <strong class="text-success">{{ product.stock }}</strong></p>
                    <p class="fs--1 mb-1"><span>Quantity: </span><strong>{{ product.remove_quantity }}</strong></p>
                    <div class="col-auto px-0">
                        <a class="btn btn-sm btn-outline-danger border-300"
                           {% if user.id|has_wishlist:product.id %}style="background-color: red; color : white"
                           {% else %} style="background-color: white; color:black"
                           {% endif %}
                                {% if user.is_authenticated %}
                           href="{% url 'wishlist_create' product.id %}" data-bs-toggle="tooltip"
                                {% else %}
                           href="{% url 'login' %}"
                                {% endif %}
                           data-bs-placement="top" title="Add to Wish List">
                                <span
                                        class="far fa-heart me-1"></span>
                            {{ product.wishlist_set.count }}
                        </a>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-12">
                    <div class="overflow-hidden mt-4">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            {#                            <li class="nav-item"><a class="nav-link active ps-0" id="description-tab"#}
                            {#                                                    data-bs-toggle="tab" href="#tab-description" role="tab"#}
                            {#                                                    aria-controls="tab-description" aria-selected="true">Description</a>#}
                            {#                            </li>#}
                            <li class="nav-item"><a class="nav-link px-2px-md-3" id="specifications-tab"
                                                    data-bs-toggle="tab" href="#tab-specifications"
                                                    role="tab" aria-controls="tab-specifications"
                                                    aria-selected="false">Specifications</a></li>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="tab-description" role="tabpanel"
                                 aria-labelledby="description-tab">
                                {#                                <div class="mt-3">#}
                                {#                                    {{ product.description|safe }}#}
                                {#                                </div>#}

                            </div>
                            <div class="tab-pane fade" id="tab-specifications" role="tabpanel"
                                 aria-labelledby="specifications-tab">
                                <table class="table fs--1 mt-3">
                                    <tbody>
                                    {% for key, value in product.characteristics.items|custom_slice:"0:4" %}
                                        <tr>
                                            <td class="bg-100" style="width: 30%;">{{ key }}</td>
                                            <td>{{ value }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="tab-reviews" role="tabpanel"
                                 aria-labelledby="reviews-tab">
                                <div class="row mt-3">
                                    <div class="col-lg-6 mb-4 mb-lg-0">
                                        <div class="mb-1"><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="ms-3 text-dark fw-semi-bold">Awesome support, great code 😍</span>
                                        </div>
                                        <p class="fs--1 mb-2 text-600">By Drik Smith • October 14, 2019</p>
                                        <p class="mb-0">You shouldn't need to read a review to see how nice
                                            and polished this theme is. So I'll tell you something you won't
                                            find in the demo. After the download I had a technical question,
                                            emailed the team and got a response right from the team CEO with
                                            helpful advice.</p>
                                        <hr class="my-4"/>
                                        <div class="mb-1"><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star text-warning fs--1"></span><span
                                                class="fa fa-star-half-alt text-warning star-icon fs--1"></span><span
                                                class="ms-3 text-dark fw-semi-bold">Outstanding Design, Awesome Support</span>
                                        </div>
                                        <p class="fs--1 mb-2 text-600">By Liane • December 14, 2019</p>
                                        <p class="mb-0">This really is an amazing template - from the style
                                            to the font - clean layout. SO worth the money! The demo pages
                                            show off what Bootstrap 4 can impressively do. Great template!!
                                            Support response is FAST and the team is amazing - communication
                                            is important.</p>
                                    </div>
                                    <div class="col-lg-6 ps-lg-5">
                                        <form>
                                            <h5 class="mb-3">Write your Review</h5>
                                            <div class="mb-3">
                                                <label class="form-label">Ratting: </label>
                                                <div class="d-block"
                                                     data-rater='{"starSize":32,"step":0.5}'></div>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label"
                                                       for="formGroupNameInput">Name:</label>
                                                <input class="form-control" id="formGroupNameInput"
                                                       type="text"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label"
                                                       for="formGroupEmailInput">Email:</label>
                                                <input class="form-control" id="formGroupEmailInput"
                                                       type="email"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label" for="formGrouptextareaInput">Review:</label>
                                                <textarea class="form-control" id="formGrouptextareaInput"
                                                          rows="3"></textarea>
                                            </div>
                                            <button class="btn btn-primary" type="submit">Submit</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-8 swiper-container">
        <form action="{% url 'order' %}" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label class="form-label" for="formGroupNameInput">Mahsulot miqdori:</label>
                <input class="form-control" name="quantity" id="formGroupNameInput" type="number">
            </div>
            <div class="mb-2">
                <label class="form-label" for="formGroupNameInput">Ism:</label>
                <input class="form-control" name="name" id="formGroupNameInput" type="text">
            </div>
            <input class="form-control" name="product" type="text" value="{{ product.id }}" hidden>

            <div class="mb-4">
                <label class="form-label" for="formGroupEmailInput">Telefon nomer:</label>
                <input class="form-control" id="phone-mask" required="" name="phone_number" type="text">
            </div>
            <span style="padding-bottom: 100px;">
                Ma`lumotlarni to`ldirganingizdan so`ng 5-10 daqiqa ichida bizning hodimlarimiz siz bilan bog`lanadi
                </span>
            <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 20px;">
                <button class="btn btn-primary" type="submit">Buyurtma berish</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/apps/ordered_list.html
{% extends 'base/base2.html' %}
{% load static %}
{% block content %}

    <div class="container text-center pb-5 card" style="margin-top: 80px;">
        <div class="card-body" style="margin-top: 30px">

        </div>

        <img style="height: 100px; width:100px; margin-left:45%; margin-top: 30px"
             src="{% static 'apps/succes_icon.png' %}"
             alt="Green Success Image">
        <h3 class="mt-4">Arizangiz qabul qilindi!</h3>
        <p>Batafsil ma'lumot uchun operator yaqin vaqt ichida siz bilan aloqaga chiqadi.</p>
        <p>Iltimos, telefoningiz yoqilgan holda bo'lsin!</p>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Mahsulot</th>
                <th scope="col">Summa</th>
                <th scope="col">Soni</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="col">{{ order.product.name }}</th>
                <th scope="col">{{ order.product.price }}</th>
                <th scope="col">1</th>
            </tr>

            <tr>
                <th scope="col">Yetkazib berish</th>
                <th scope="col">{{ delivery_price }}</th>
            </tr>

            </tbody>
        </table>
        <div class="row">
            <div class="col-md-6">
                <h5>Jami</h5>
                <h5>{{ delivery_price|add:order.product.price }} so'm</h5>
            </div>
            <div class="col-md-6 mt-3">
                <a href="/" class="btn btn-primary w-50">Boshqa mahsulotlar</a>
            </div>
        </div>
    </div>
{% endblock %}